{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ipmaze-controller.serviceAccountName" . }}
  namespace: {{ include "ipmaze-controller.targetNamespace" . }}
  labels:
    {{- include "ipmaze-controller.labels" . | nindent 4 }}
{{- end }}
