apiVersion: ipmaze.k8s.justin.directory/v1alpha1
kind: CIDRPolicy
metadata:
  name: microsoft-storage-westus
  namespace: default
spec:
  source:
    address: https://mirror.example.com/microsoft-service-tags.json
    jmesPath: values[?name=='Storage.WestUS'].properties.addressPrefixes[]
  target:
    podSelector:
      matchLabels:
        app: api
  rules:
    - directions:
        - ingress
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress
