apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
images:
  - name: REPLACE_IMAGE
    newName: ghcr.io/justinbrick-tta/ipmaze-controller
    newTag: latest
